### ISSUE TITLE
KSP2: KaInvalidLifetimeOwnerAccessException in KspContributesSubcomponentHandlerSymbolProcessor

### ISSUE THREAD

**Issue by gabrielittner** [ZacSweers/anvil#39]
With KSP 2.0.0-1.0.24 where the KSP2 `IllegalAccessError` is fixed I've started running into `e: [ksp] ksp.org.jetbrains.kotlin.analysis.api.lifetime.KaInvalidLifetimeOwnerAccessException: Access to invalid ksp.org.jetbrains.kotlin.analysis.api.platform.lifetime.KotlinAlwaysAccessibleLifetimeToken@16c9df1: PSI has changed since creation`

It could be a KSP issue (https://github.com/google/ksp/issues/1854) or an issue with how the processor is implemented (see the kotlin-inject commits linked in that issue). 

```
apCaused by: ksp.org.jetbrains.kotlin.analysis.api.lifetime.KaInvalidLifetimeOwnerAccessException: Access to invalid ksp.org.jetbrains.kotlin.analysis.api.platform.lifetime.KotlinAlwaysAccessibleLifetimeToken@16c9df1: PSI has changed since creation
        at ksp.org.jetbrains.kotlin.analysis.api.fir.components.KaFirTypeRelationChecker.semanticallyEquals(KaFirTypeRelationChecker.kt:60)
        at ksp.org.jetbrains.kotlin.analysis.api.impl.base.KaBaseSession.semanticallyEquals(KaBaseSession.kt)
        at ksp.org.jetbrains.kotlin.analysis.api.components.KaTypeRelationChecker.semanticallyEquals$default(KaTypeRelationChecker.kt:15)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSTypeImpl.equals(KSTypeImpl.kt:170)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:169)
        at com.squareup.anvil.compiler.codegen.KspContributesSubcomponentHandlerSymbolProcessor$Trigger.equals(KspContributesSubcomponentHandlerSymbolProcessor.kt:447)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:130)
        at com.squareup.anvil.compiler.codegen.KspContributesSubcomponentHandlerSymbolProcessor.computePendingEvents(KspContributesSubcomponentHandlerSymbolProcessor.kt:246)
        at com.squareup.anvil.compiler.KspContributionMerger.processChecked(KspContributionMerger.kt:130)
        at com.squareup.anvil.compiler.codegen.ksp.AnvilSymbolProcessor.process(AnvilSymbolProcessing.kt:31)
        at com.squareup.anvil.compiler.ClassScanningKspProcessor.processChecked(ClassScanningKspProcessor.kt:50)
        at com.squareup.anvil.compiler.codegen.ksp.AnvilSymbolProcessor.process(AnvilSymbolProcessing.kt:31)
        at com.google.devtools.ksp.impl.KotlinSymbolProcessing.execute(KotlinSymbolProcessing.kt:538)
        at com.google.devtools.ksp.impl.KSPLoader$Companion.loadAndRunKSP(KSPLoader.kt:36)
        at com.google.devtools.ksp.impl.KSPLoader.loadAndRunKSP(KSPLoader.kt)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at com.google.devtools.ksp.gradle.KspAAWorkerAction.execute(KspAATask.kt:510)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:195)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:128)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:170)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:267)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:131)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:136)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:165)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:134)
        ... 2 more
```

**Comment by ZacSweers** [comment]
Interesting, thanks for the report. I'll look at doing similar workarounds

**Comment by ZacSweers** [comment]
Could be a little more involved than I thought it would in ContributesSubcomponent handling, but I think I can find a path through. Gonna cut a 0.2.0 release right now with latest changes to let those bake though
