### ISSUE TITLE
`@AssistedInject` doesn't seem to work with typealiased parameters

### ISSUE THREAD

**Issue by jmartinesp** [ZacSweers/anvil#52]
Hello, first of all, thanks for the fork! I've been wanting to test Anvil using KSP against our codebase for a while but I never found good instructions on how to do that.

As I was trying to migrate our project to using this fork I think I got almost everything working, but I'm stuck at one point: we have several classes like this:

```kotlin
class FooPresenter @AssistedInject constructor(...) : Presenter<FooState> {
    interface Factory {
        fun create(bar: Bar): FooPresenter
    }
}
```

With the latest Anvil stable version this worked as expected, but with Anvil + KSP I got these kind of errors for these type of classes:

```
> Task :features:roomdetails:impl:compileDebugJavaWithJavac FAILED
/Users/jorge/Developer/Element/element-x-android/features/roomdetails/impl/build/generated/ksp/debug/java/io/element/android/features/roomdetails/impl/members/details/RoomMemberDetailsPresenter_Factory.java:51: error: RoomMemberDetailsPresenter(String,MatrixClient,MatrixRoom,StartDMAction) has private access in RoomMemberDetailsPresenter
    return new RoomMemberDetailsPresenter(roomMemberId, client, room, startDMAction);
           ^
1 error
```

I thought maybe it would work if I added the `@AssistedFactory` annotation to the factory, but then I got:

```
e: [ksp] java.lang.IllegalArgumentException: not a valid name: create-gv-vgKQ
        at com.squareup.javapoet.Util.checkArgument(Util.java:53)
        at com.squareup.javapoet.MethodSpec$Builder.setName(MethodSpec.java:315)
        at com.squareup.javapoet.MethodSpec$Builder.<init>(MethodSpec.java:310)
        at com.squareup.javapoet.MethodSpec$Builder.<init>(MethodSpec.java:294)
        at com.squareup.javapoet.MethodSpec.methodBuilder(MethodSpec.java:188)
        at dagger.internal.codegen.xprocessing.MethodSpecs.overriding(MethodSpecs.java:38)
        at dagger.internal.codegen.processingstep.AssistedFactoryProcessingStep$AssistedFactoryImplGenerator.topLevelTypes(AssistedFactoryProcessingStep.java:302)
        at dagger.internal.codegen.processingstep.AssistedFactoryProcessingStep$AssistedFactoryImplGenerator.topLevelTypes(AssistedFactoryProcessingStep.java:228)
        at dagger.internal.codegen.base.SourceFileGenerator.generate(SourceFileGenerator.java:70)
        at dagger.internal.codegen.processingstep.AssistedFactoryProcessingStep.process(AssistedFactoryProcessingStep.java:113)
        at dagger.internal.codegen.processingstep.AssistedFactoryProcessingStep.process(AssistedFactoryProcessingStep.java:76)
        at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:94)
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:297)
        at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:72)
        at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:49)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.XProcessingStep.process(XProcessingStep.kt:59)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:132)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspBasicAnnotationProcessor.process(KspBasicAnnotationProcessor.kt:62)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:75)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze$lambda$12(KotlinToJVMBytecodeCompiler.kt:373)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:364)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runFrontendAndGenerateIrUsingClassicFrontend(KotlinToJVMBytecodeCompiler.kt:195)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:106)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:176)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1556)
        at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

So I'm not sure how to proceed. I'm not an expert in DI, or Dagger so I might have done something wrong while migrating, but I couldn't find what, so maybe it's a bug.

If you want a repro you can use [this branch](https://github.com/element-hq/element-x-android/tree/wip/anvil-ksp-fork) while running `./gradlew :app:assembleGplayDebug`. `RoomMemberDetailsPresenter` is one good example of this behaviour, but there are several `class *Presenter @AssistedInject` around having the same issue.

We are also using a custom anvil code generator which I migrated to KSP (the `:anvilcodegen` module), in case that might affect the result.

**Comment by jmartinesp** [comment]
Oh, I think I found the issue. The problem is not the `@AssistedFactory` annotation at all, it's the fact that the param used in the factory is a typealias 🫤 . `UserId` in this case is actually a wrapper for `String`, and all other problematic places also used similar typealiases. I guess this is a Dagger KSP issue, not an Anvil one.

**Comment by ZacSweers** [comment]
Yeah dagger-ksp has some issues with typealias handling, please file on the dagger repo with a repro :)
